apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama-container
        image: ollama/ollama:0.5.8-rc7  # Replace with the actual Ollama image
        ports:
        - containerPort: 11434  # Replace with the actual port Ollama uses
        resources:
          requests:
            memory: "256Mi"  # Request 256 MiB of memory
            cpu: "250m"      # Request 250 millicores of CPU
          limits:
            memory: "512Mi"  # Limit to 512 MiB of memory
            cpu: "500m"      # Limit to 500 millicores of CPU